version: '3.7'

services:
  ustj-foodpantrycontrol-webapi:
    image: ${DOCKER_REGISTRY-}ustj-foodpantrycontrol-webapi
    build:
      context: .
      dockerfile: br.com.ustj.FoodPantryControl.Webapi/Dockerfile
    networks:
      - ustj-foodpantrycontrol-network

volumes:
  pgservers:
  pgdata:

networks:
  ustj-foodpantrycontrol-network: